apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalyst.configmapName" . }}
  labels:
    {{- include "catalyst.labels" . | nindent 4 }}
data:
  SSH_HOST: {{ .Values.ssh.host | quote }}
  SSH_PORT: {{ .Values.ssh.port | quote }}
  SSH_USER: {{ .Values.ssh.user | quote }}
  IDEAS_BASE_PATH: {{ .Values.ssh.ideasBasePath | quote }}
