{{- if not .Values.secrets.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalyst.secretsName" . }}
  labels:
    {{- include "catalyst.labels" . | nindent 4 }}
type: Opaque
stringData:
  CATALYST_SECRET: {{ .Values.secrets.catalystSecret | quote }}
  COOKIE_SECRET: {{ .Values.secrets.cookieSecret | quote }}
{{- end }}
